<a href="https://colab.research.google.com/github/ajwkim/NSM_PDL/blob/main/PDL_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Intelligence & Machine Learning
- 특성 추출 from data: scikit-learn
- kaggle.com

## Deep Learning (DL)
- 1989: neural networks (nn) and DL as a way of replacing any mathematical function in an approximate way(George Cybenko, Approximation by Superpositions of Sigmoidal Functions)
- GPU for gaming : performance & affordability
- 2009: training nn is based on performing lots of matrix operations and these GPUs can speed up training as well as make larger, deeper architectures(Rajat Raina et al., Large-Scale Deep Unsupervised Learning Using Graphics Processors)
- 2010s: Dropout 등 DL technic 발전 -> TPU
- 2012년까지 ImageNet competition (14 million+ pictures, manually labeled into 20000 categories) error rate 25% -> DL(AlexNet w/ MaxPool, Dropout, ReLU) 16%로 우승
- 2015, ResNet(Microsoft) 3.6% (사람 평균 5%)

## Deep Reinforcement Learning (DRL)
- dynamic programming (DP) and optimal control =>
- Deep Reinforcement Learning
- Markov Decision Process (MDP)
- given state, take action, and observe next_state and reward => maximize total discounted reward

# pytorch
- open source library released by formerly Facebook(now Meta) in 2017
- rivaled by Keras/Tensorflow (Google)
- 일관된/Pythonic 문법으로 연구용/논문 대다수에서 활용
- 설치: pytorch.org

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'             # 셀 내 모든 값 프린트, 기본은 'last_expr'

In [3]:
import torch
import numpy as np

torch.__version__
np.__version__

'2.6.0+cu124'

'2.0.2'

## tensor

In [4]:
# 텐서 생성 및 텐서의 속성

data = [[1, 2], [3, 4]]
a = np.array(data)

t = torch.tensor(data)      # tensor creation from data

t.shape         # t.size()
t.dtype         # inferred dtype(int64)
t.ndim          # t.dim()

t.device
t.requires_grad

torch.Size([2, 2])

torch.int64

2

device(type='cpu')

False

In [5]:
t = torch.tensor([[1., 2], [3, 4]])

t.dtype         # inferred dtype(float32)

torch.float32

In [6]:
# tensor creation from ndarray

a = np.array(data)
a
a.dtype

t = torch.from_numpy(a)     # torch.tensor(a)
t
t.dtype

array([[1, 2],
       [3, 4]])

dtype('int64')

tensor([[1, 2],
        [3, 4]])

torch.int64

In [7]:
t.numpy()       # tensor -> ndarray
t.tolist()      # tensor -> list

array([[1, 2],
       [3, 4]])

[[1, 2], [3, 4]]

In [8]:
# tensor creation : float32, Double, Long, ...

t = torch.FloatTensor(data)     # float32
t = torch.Tensor(data)
# 텐서.float()

t.dtype

torch.float32

In [9]:
torch.FloatTensor(2, 3)         # *size
torch.Tensor(2, 3)

tensor([[-8.8988e+18,  4.3161e-41, -8.8988e+18],
        [ 4.3161e-41,  6.6380e-07,  1.0243e-11]])

tensor([[-8.8987e+18,  4.3161e-41,  1.6462e+01],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [11]:
torch.zeros(2, 3)               # *size, float32
torch.zeros(2, 3).dtype

tensor([[0., 0., 0.],
        [0., 0., 0.]])

torch.float32

In [12]:
torch.ones(2, 3)                # *size, float32
torch.ones(2, 3).dtype

tensor([[1., 1., 1.],
        [1., 1., 1.]])

torch.float32

In [ ]:
# torch.DoubleTensor        # float64

# torch.LongTensor          # int64
# t.long()

# t.int()                   # int32

# torch.ByteTensor          # uint8
# t.byte()