<a href="https://colab.research.google.com/github/ajwkim/NSM_PDL/blob/main/PDL_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Intelligence & Machine Learning
- 특성 추출 from data: scikit-learn
- kaggle.com

## Deep Learning (DL)
- 1989: neural networks (nn) and DL as a way of replacing any mathematical function in an approximate way(George Cybenko, Approximation by Superpositions of Sigmoidal Functions)
- GPU for gaming : performance & affordability
- 2009: training nn is based on performing lots of matrix operations and these GPUs can speed up training as well as make larger, deeper architectures(Rajat Raina et al., Large-Scale Deep Unsupervised Learning Using Graphics Processors)
- 2010s: Dropout 등 DL technic 발전 -> TPU
- 2012년까지 ImageNet competition (14 million+ pictures, manually labeled into 20000 categories) error rate 25% -> DL(AlexNet w/ MaxPool, Dropout, ReLU) 16%로 우승
- 2015, ResNet(Microsoft) 3.6% (사람 평균 5%)

## Deep Reinforcement Learning (DRL)
- dynamic programming (DP) and optimal control =>
- Deep Reinforcement Learning
- Markov Decision Process (MDP)
- given state, take action, and observe next_state and reward => maximize total discounted reward

# pytorch
- open source library released by formerly Facebook(now Meta) in 2017
- rivaled by Keras/Tensorflow (Google)
- 일관된/Pythonic 문법으로 연구용/논문 대다수에서 활용
- 설치: pytorch.org

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'             # 셀 내 모든 값 프린트, 기본은 'last_expr'

In [ ]:
import torch
import numpy as np

torch.__version__
np.__version__

'2.6.0+cu124'

'2.0.2'

In [ ]:
torch.cuda.is_available()       # nvidia gpu (colab)

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

True

'cuda'

## tensor

In [ ]:
# 텐서 생성 및 텐서의 속성

data = [[1, 2], [3, 4]]
a = np.array(data)          # ndarray creation from data

t = torch.tensor(data)      # tensor creation from data

t.shape         # t.size()
t.dtype         # inferred dtype(int64)
t.ndim          # t.dim()

t.device
t.requires_grad

torch.Size([2, 2])

torch.int64

2

device(type='cpu')

False

In [ ]:
# cpu <-> gpu(cuda)

t.cuda()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
t_ = t.to(device)
t_

t_.cpu()
t_.to('cpu')

tensor([[1, 2],
        [3, 4]], device='cuda:0')

tensor([[1, 2],
        [3, 4]], device='cuda:0')

tensor([[1, 2],
        [3, 4]])

tensor([[1, 2],
        [3, 4]])

In [ ]:
t = torch.tensor([[1., 2], [3, 4]])

t.dtype         # inferred dtype(float32)

torch.float32

In [ ]:
# tensor creation from ndarray

a = np.array(data)
a
a.dtype

t = torch.from_numpy(a)     # torch.tensor(a)
t
t.dtype

array([[1, 2],
       [3, 4]])

dtype('int64')

tensor([[1, 2],
        [3, 4]])

torch.int64

In [ ]:
t.numpy()       # tensor -> ndarray
t.tolist()      # tensor -> list

array([[1, 2],
       [3, 4]])

[[1, 2], [3, 4]]

In [ ]:
# tensor creation : float32, Double, Long, ...

t = torch.FloatTensor(data)     # float32
t = torch.Tensor(data)
# 텐서.float()

t.dtype

torch.float32

In [ ]:
torch.FloatTensor(2, 3)         # *size
torch.Tensor(2, 3)

tensor([[-8.8988e+18,  4.3161e-41, -8.8988e+18],
        [ 4.3161e-41,  6.6380e-07,  1.0243e-11]])

tensor([[-8.8987e+18,  4.3161e-41,  1.6462e+01],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])

In [ ]:
torch.zeros(2, 3)               # *size, float32
torch.zeros(2, 3).dtype

tensor([[0., 0., 0.],
        [0., 0., 0.]])

torch.float32

In [ ]:
torch.ones(2, 3)                # *size, float32
torch.ones(2, 3).dtype

tensor([[1., 1., 1.],
        [1., 1., 1.]])

torch.float32

In [ ]:
# torch.DoubleTensor        # float64

# torch.LongTensor          # int64
# t.long()

# t.int()                   # int32

# torch.ByteTensor          # uint8
# t.byte()

In [ ]:
torch.ones(2, 3)        # *size, float32
torch.ones((2, 3))

torch.zeros(2, 3)       # *size, float32
torch.zeros((2, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.rand(2, 3)        # *size, [0, 1)
torch.rand((2, 3))

tensor([[0.2818, 0.6344, 0.1961],
        [0.1462, 0.0573, 0.2825]])

tensor([[0.3682, 0.9639, 0.3856],
        [0.7756, 0.7282, 0.6511]])

In [ ]:
torch.randperm(10)      # dtype=torch.int64

tensor([3, 6, 5, 1, 9, 4, 7, 8, 0, 2])

In [ ]:
# same dtype & shape

# torch.ones_like(텐서)
# torch.zeros_like(텐서)
# torch.rand_like(텐서)

In [ ]:
# scalar tensor -> scalar

torch.tensor(1)
torch.tensor(1).item()

torch.tensor([0])
torch.tensor([0]).item()

torch.tensor([[0]])
torch.tensor([[0]]).item()

tensor(1)

1

tensor([0])

0

tensor([[0]])

0

In [ ]:
# 다차원 indexing & slicing : same as ndarray

In [ ]:
# 텐서.reshape(*size)
# 텐서.view(*size)          # for contiguous tensors only

In [ ]:
hwc = torch.rand(640, 480, 3)       # 일반적으로 (height, width, channel) 이미지
chw = hwc.permute(2, 0, 1)          # PyTorch (channel, height, width) 이미지
chw.shape

torch.Size([3, 640, 480])

In [ ]:
# 텐서.squeeze/unsqueeze

t = torch.tensor(np.arange(1, 5).reshape(2, -1)).float()
t = torch.Tensor(np.arange(1, 5)).reshape(2, -1)
t = torch.arange(1, 5, dtype=torch.float32).reshape(2, -1)
t
t.shape

t_ = t.unsqueeze(0)
t_
t_.shape

tensor([[1., 2.],
        [3., 4.]])

torch.Size([2, 2])

tensor([[[1., 2.],
         [3., 4.]]])

torch.Size([1, 2, 2])

In [ ]:
t.unsqueeze(1).shape
t.unsqueeze(-1).shape

torch.Size([2, 1, 2])

torch.Size([2, 2, 1])

In [ ]:
t_.squeeze()        # 차원의 크기가 1인 모든 차원을 없애줌
t_.squeeze().shape

tensor([[1., 2.],
        [3., 4.]])

torch.Size([2, 2])

In [ ]:
t_ = t.reshape(-1, 2, 2)
t_.shape

t_.reshape(2, -1).shape

torch.Size([1, 2, 2])

torch.Size([2, 2])

In [ ]:
# 텐서.split/chunk

t = torch.Tensor(10, 3)

splits = t.split(4)         # 텐서.split(원하는size, dim=0)

type(splits)
for s in splits:
    print(s)
    print(s.shape)
    print()

tuple

tensor([[7.4058e-37, 4.1410e-33, 2.3850e-42],
        [2.3920e-42, 0.0000e+00, 3.0454e-33],
        [1.7740e-41, 0.0000e+00, 0.0000e+00],
        [1.0980e-32, 9.5008e-43, 9.5709e-43]])
torch.Size([4, 3])

tensor([[0.0000e+00, 9.1835e-41, 1.8458e-41],
        [0.0000e+00, 0.0000e+00, 9.4756e-42],
        [0.0000e+00, 1.8958e-34, 9.8343e-42],
        [0.0000e+00, 3.0333e-33, 6.6265e-32]])
torch.Size([4, 3])

tensor([[1.3088e-42, 1.3158e-42, 0.0000e+00],
        [1.2182e-32, 4.2254e-38, 7.9474e-34]])
torch.Size([2, 3])



In [ ]:
chunks = t.chunk(3)         # 텐서.chunk(총 개수, dim=0)

type(chunks)
for c in chunks:
    print(c)
    print(c.shape)
    print()

tuple

tensor([[7.4058e-37, 4.1410e-33, 2.3850e-42],
        [2.3920e-42, 0.0000e+00, 3.0454e-33],
        [1.7740e-41, 0.0000e+00, 0.0000e+00],
        [1.0980e-32, 9.5008e-43, 9.5709e-43]])
torch.Size([4, 3])

tensor([[0.0000e+00, 9.1835e-41, 1.8458e-41],
        [0.0000e+00, 0.0000e+00, 9.4756e-42],
        [0.0000e+00, 1.8958e-34, 9.8343e-42],
        [0.0000e+00, 3.0333e-33, 6.6265e-32]])
torch.Size([4, 3])

tensor([[1.3088e-42, 1.3158e-42, 0.0000e+00],
        [1.2182e-32, 4.2254e-38, 7.9474e-34]])
torch.Size([2, 3])



In [ ]:
# 텐서.index_select

t = torch.Tensor([[[1, 1], [2, 2]],
                  [[3, 3], [4, 4]],
                  [[5, 5], [6, 6]]])
t.shape

ixs = torch.LongTensor([2, 1])
t_ = t.index_select(dim=0, index=ixs)       # 텐서.index_select(dim, index)
t_
t_.shape

torch.Size([3, 2, 2])

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])

torch.Size([2, 2, 2])

In [ ]:
# torch.cat([텐서1, 텐서2], dim=0)

t1 = torch.Tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.Tensor([[10, 11, 12], [13, 14, 15]])

t3 = torch.cat([t1, t2])        # dim=0
t3
t3.shape

t4 = torch.cat([t1, t2], dim=-1)
t4
t4.shape

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [10., 11., 12.],
        [13., 14., 15.]])

torch.Size([4, 3])

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.]])

torch.Size([2, 6])

In [ ]:
# torch.stack([텐서1, 텐서2], dim=0)

t5 = torch.stack([t1, t2])
t5
t5.shape

t6 = torch.stack([t1, t2], dim=-1)
t6
t6.shape

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[10., 11., 12.],
         [13., 14., 15.]]])

torch.Size([2, 2, 3])

tensor([[[ 1., 10.],
         [ 2., 11.],
         [ 3., 12.]],

        [[ 4., 13.],
         [ 5., 14.],
         [ 6., 15.]]])

torch.Size([2, 3, 2])

In [ ]:
t = torch.Tensor([[1, 2], [3, 4]])

torch.sum(t)
t.sum()
t.sum().item()

t.sum(dim=-1)
t.sum(dim=-1, keepdim=True)

tensor(10.)

tensor(10.)

10.0

tensor([3., 7.])

tensor([[3.],
        [7.]])

In [ ]:
t = torch.randperm(3**3).reshape(3, 3, -1)  # (3, 3, 3)
t

t.argmax(-1)                # (3, 3)
t.argmax(-1, keepdim=True)  # (3, 3, 1)

tensor([[[ 4,  3, 10],
         [11,  9, 22],
         [26, 25,  0]],

        [[16, 13, 23],
         [ 8, 21, 14],
         [ 5, 12, 15]],

        [[ 1,  2, 20],
         [24, 19, 17],
         [18,  6,  7]]])

tensor([[2, 2, 0],
        [2, 1, 2],
        [2, 0, 0]])

tensor([[[2],
         [2],
         [0]],

        [[2],
         [1],
         [2]],

        [[2],
         [0],
         [0]]])